/*
 * Testing API
 * Xyte's Device Cloud is the first all-in-one servitization platform designed for device and hardware manufacturers to cloudify, operate, support, and commercialize their connected devices in a unified platform.   We enable OEMs across different industries to navigate their digital journey, transforming their devices into integrated business solutions that combine hardware, software and services. The only business and commerce platform designed specifically for IoT device manufacturers, our fully-federated Device Cloud empowers OEMs to manage the complete lifecycle of their devices, from the minute they leave the warehouse through aftermarket sales to end customers.  Our out-of-the-box applications for asset management, remote support, ecommerce and subscription management, financing, and a powerful and secure back office suite help OEMs boost revenue and market growth, optimize operational efficiencies, gain instant insights into equipment and device performance, and develop sustainable customer relationships.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.DeviceListDevicesResponseDataInnerFirmware;
import com.konfigthis.client.model.DeviceListDevicesResponseDataInnerModel;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for DeviceListDevicesResponseDataInner
 */
public class DeviceListDevicesResponseDataInnerTest {
    private final DeviceListDevicesResponseDataInner model = new DeviceListDevicesResponseDataInner();

    /**
     * Model tests for DeviceListDevicesResponseDataInner
     */
    @Test
    public void testDeviceListDevicesResponseDataInner() {
        // TODO: test DeviceListDevicesResponseDataInner
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'sn'
     */
    @Test
    public void snTest() {
        // TODO: test sn
    }

    /**
     * Test the property 'mac'
     */
    @Test
    public void macTest() {
        // TODO: test mac
    }

    /**
     * Test the property 'cloudId'
     */
    @Test
    public void cloudIdTest() {
        // TODO: test cloudId
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'lastSeenAt'
     */
    @Test
    public void lastSeenAtTest() {
        // TODO: test lastSeenAt
    }

    /**
     * Test the property 'details'
     */
    @Test
    public void detailsTest() {
        // TODO: test details
    }

    /**
     * Test the property 'state'
     */
    @Test
    public void stateTest() {
        // TODO: test state
    }

    /**
     * Test the property 'model'
     */
    @Test
    public void modelTest() {
        // TODO: test model
    }

    /**
     * Test the property 'firmware'
     */
    @Test
    public void firmwareTest() {
        // TODO: test firmware
    }

}
