/*
 * Testing API
 * Xyte's Device Cloud is the first all-in-one servitization platform designed for device and hardware manufacturers to cloudify, operate, support, and commercialize their connected devices in a unified platform.   We enable OEMs across different industries to navigate their digital journey, transforming their devices into integrated business solutions that combine hardware, software and services. The only business and commerce platform designed specifically for IoT device manufacturers, our fully-federated Device Cloud empowers OEMs to manage the complete lifecycle of their devices, from the minute they leave the warehouse through aftermarket sales to end customers.  Our out-of-the-box applications for asset management, remote support, ecommerce and subscription management, financing, and a powerful and secure back office suite help OEMs boost revenue and market growth, optimize operational efficiencies, gain instant insights into equipment and device performance, and develop sustainable customer relationships.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.DeviceSendChildTelemetriesResponse11303e815d564910A47268676375d995;
import com.konfigthis.client.model.DeviceSendChildTelemetriesResponseB4adc7484462493381739d40e0a17d22;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for DeviceSendChildTelemetriesResponse
 */
public class DeviceSendChildTelemetriesResponseTest {
    private final DeviceSendChildTelemetriesResponse model = new DeviceSendChildTelemetriesResponse();

    /**
     * Model tests for DeviceSendChildTelemetriesResponse
     */
    @Test
    public void testDeviceSendChildTelemetriesResponse() {
        // TODO: test DeviceSendChildTelemetriesResponse
    }

    /**
     * Test the property '_11303e815d564910A47268676375d995'
     */
    @Test
    public void _11303e815d564910A47268676375d995Test() {
        // TODO: test _11303e815d564910A47268676375d995
    }

    /**
     * Test the property 'b4adc7484462493381739d40e0a17d22'
     */
    @Test
    public void b4adc7484462493381739d40e0a17d22Test() {
        // TODO: test b4adc7484462493381739d40e0a17d22
    }

}
