/*
 * Testing API
 * Xyte's Device Cloud is the first all-in-one servitization platform designed for device and hardware manufacturers to cloudify, operate, support, and commercialize their connected devices in a unified platform.   We enable OEMs across different industries to navigate their digital journey, transforming their devices into integrated business solutions that combine hardware, software and services. The only business and commerce platform designed specifically for IoT device manufacturers, our fully-federated Device Cloud empowers OEMs to manage the complete lifecycle of their devices, from the minute they leave the warehouse through aftermarket sales to end customers.  Our out-of-the-box applications for asset management, remote support, ecommerce and subscription management, financing, and a powerful and secure back office suite help OEMs boost revenue and market growth, optimize operational efficiencies, gain instant insights into equipment and device performance, and develop sustainable customer relationships.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for DeviceSendChildTelemetriesResponseB4adc7484462493381739d40e0a17d22
 */
public class DeviceSendChildTelemetriesResponseB4adc7484462493381739d40e0a17d22Test {
    private final DeviceSendChildTelemetriesResponseB4adc7484462493381739d40e0a17d22 model = new DeviceSendChildTelemetriesResponseB4adc7484462493381739d40e0a17d22();

    /**
     * Model tests for DeviceSendChildTelemetriesResponseB4adc7484462493381739d40e0a17d22
     */
    @Test
    public void testDeviceSendChildTelemetriesResponseB4adc7484462493381739d40e0a17d22() {
        // TODO: test DeviceSendChildTelemetriesResponseB4adc7484462493381739d40e0a17d22
    }

    /**
     * Test the property 'configVersion'
     */
    @Test
    public void configVersionTest() {
        // TODO: test configVersion
    }

    /**
     * Test the property 'command'
     */
    @Test
    public void commandTest() {
        // TODO: test command
    }

    /**
     * Test the property 'infoVersion'
     */
    @Test
    public void infoVersionTest() {
        // TODO: test infoVersion
    }

    /**
     * Test the property 'newLicenses'
     */
    @Test
    public void newLicensesTest() {
        // TODO: test newLicenses
    }

    /**
     * Test the property 'latestFwVersion'
     */
    @Test
    public void latestFwVersionTest() {
        // TODO: test latestFwVersion
    }

    /**
     * Test the property 'latestFwFileId'
     */
    @Test
    public void latestFwFileIdTest() {
        // TODO: test latestFwFileId
    }

    /**
     * Test the property 'spaceDataVersion'
     */
    @Test
    public void spaceDataVersionTest() {
        // TODO: test spaceDataVersion
    }

    /**
     * Test the property 'success'
     */
    @Test
    public void successTest() {
        // TODO: test success
    }

}
