/*
 * Testing API
 * Xyte's Device Cloud is the first all-in-one servitization platform designed for device and hardware manufacturers to cloudify, operate, support, and commercialize their connected devices in a unified platform.   We enable OEMs across different industries to navigate their digital journey, transforming their devices into integrated business solutions that combine hardware, software and services. The only business and commerce platform designed specifically for IoT device manufacturers, our fully-federated Device Cloud empowers OEMs to manage the complete lifecycle of their devices, from the minute they leave the warehouse through aftermarket sales to end customers.  Our out-of-the-box applications for asset management, remote support, ecommerce and subscription management, financing, and a powerful and secure back office suite help OEMs boost revenue and market growth, optimize operational efficiencies, gain instant insights into equipment and device performance, and develop sustainable customer relationships.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * DeviceUpdateDeviceRequest
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class DeviceUpdateDeviceRequest {
  public static final String SERIALIZED_NAME_FIRMWARE_VERSION = "firmware_version";
  @SerializedName(SERIALIZED_NAME_FIRMWARE_VERSION)
  private String firmwareVersion;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_SPACE_VERSION = "space_version";
  @SerializedName(SERIALIZED_NAME_SPACE_VERSION)
  private String spaceVersion;

  public static final String SERIALIZED_NAME_CONFIG_VERSION = "config_version";
  @SerializedName(SERIALIZED_NAME_CONFIG_VERSION)
  private String configVersion;

  public static final String SERIALIZED_NAME_DETAILS = "details";
  @SerializedName(SERIALIZED_NAME_DETAILS)
  private Object details;

  public DeviceUpdateDeviceRequest() {
  }

  public DeviceUpdateDeviceRequest firmwareVersion(String firmwareVersion) {
    
    
    
    
    this.firmwareVersion = firmwareVersion;
    return this;
  }

   /**
   * Get firmwareVersion
   * @return firmwareVersion
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getFirmwareVersion() {
    return firmwareVersion;
  }


  public void setFirmwareVersion(String firmwareVersion) {
    
    
    
    this.firmwareVersion = firmwareVersion;
  }


  public DeviceUpdateDeviceRequest name(String name) {
    
    
    
    
    this.name = name;
    return this;
  }

   /**
   * Friendly device name
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Friendly device name")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    
    
    
    this.name = name;
  }


  public DeviceUpdateDeviceRequest spaceVersion(String spaceVersion) {
    
    
    
    
    this.spaceVersion = spaceVersion;
    return this;
  }

   /**
   * Latest version of the space information the device has applied
   * @return spaceVersion
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Latest version of the space information the device has applied")

  public String getSpaceVersion() {
    return spaceVersion;
  }


  public void setSpaceVersion(String spaceVersion) {
    
    
    
    this.spaceVersion = spaceVersion;
  }


  public DeviceUpdateDeviceRequest configVersion(String configVersion) {
    
    
    
    
    this.configVersion = configVersion;
    return this;
  }

   /**
   * Latest version of the configuration the device has applied
   * @return configVersion
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Latest version of the configuration the device has applied")

  public String getConfigVersion() {
    return configVersion;
  }


  public void setConfigVersion(String configVersion) {
    
    
    
    this.configVersion = configVersion;
  }


  public DeviceUpdateDeviceRequest details(Object details) {
    
    
    
    
    this.details = details;
    return this;
  }

   /**
   * Details of the device. Will be visible in a different tab on the device&#39;s view calls &#39;Details&#39;.
   * @return details
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Details of the device. Will be visible in a different tab on the device's view calls 'Details'.")

  public Object getDetails() {
    return details;
  }


  public void setDetails(Object details) {
    
    
    
    this.details = details;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the DeviceUpdateDeviceRequest instance itself
   */
  public DeviceUpdateDeviceRequest putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeviceUpdateDeviceRequest deviceUpdateDeviceRequest = (DeviceUpdateDeviceRequest) o;
    return Objects.equals(this.firmwareVersion, deviceUpdateDeviceRequest.firmwareVersion) &&
        Objects.equals(this.name, deviceUpdateDeviceRequest.name) &&
        Objects.equals(this.spaceVersion, deviceUpdateDeviceRequest.spaceVersion) &&
        Objects.equals(this.configVersion, deviceUpdateDeviceRequest.configVersion) &&
        Objects.equals(this.details, deviceUpdateDeviceRequest.details)&&
        Objects.equals(this.additionalProperties, deviceUpdateDeviceRequest.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(firmwareVersion, name, spaceVersion, configVersion, details, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeviceUpdateDeviceRequest {\n");
    sb.append("    firmwareVersion: ").append(toIndentedString(firmwareVersion)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    spaceVersion: ").append(toIndentedString(spaceVersion)).append("\n");
    sb.append("    configVersion: ").append(toIndentedString(configVersion)).append("\n");
    sb.append("    details: ").append(toIndentedString(details)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("firmware_version");
    openapiFields.add("name");
    openapiFields.add("space_version");
    openapiFields.add("config_version");
    openapiFields.add("details");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to DeviceUpdateDeviceRequest
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!DeviceUpdateDeviceRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in DeviceUpdateDeviceRequest is not found in the empty JSON string", DeviceUpdateDeviceRequest.openapiRequiredFields.toString()));
        }
      }
      if ((jsonObj.get("firmware_version") != null && !jsonObj.get("firmware_version").isJsonNull()) && !jsonObj.get("firmware_version").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `firmware_version` to be a primitive type in the JSON string but got `%s`", jsonObj.get("firmware_version").toString()));
      }
      if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if ((jsonObj.get("space_version") != null && !jsonObj.get("space_version").isJsonNull()) && !jsonObj.get("space_version").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `space_version` to be a primitive type in the JSON string but got `%s`", jsonObj.get("space_version").toString()));
      }
      if ((jsonObj.get("config_version") != null && !jsonObj.get("config_version").isJsonNull()) && !jsonObj.get("config_version").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `config_version` to be a primitive type in the JSON string but got `%s`", jsonObj.get("config_version").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!DeviceUpdateDeviceRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'DeviceUpdateDeviceRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<DeviceUpdateDeviceRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(DeviceUpdateDeviceRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<DeviceUpdateDeviceRequest>() {
           @Override
           public void write(JsonWriter out, DeviceUpdateDeviceRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public DeviceUpdateDeviceRequest read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             DeviceUpdateDeviceRequest instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of DeviceUpdateDeviceRequest given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of DeviceUpdateDeviceRequest
  * @throws IOException if the JSON string is invalid with respect to DeviceUpdateDeviceRequest
  */
  public static DeviceUpdateDeviceRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, DeviceUpdateDeviceRequest.class);
  }

 /**
  * Convert an instance of DeviceUpdateDeviceRequest to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

