/*
 * Testing API
 * Xyte's Device Cloud is the first all-in-one servitization platform designed for device and hardware manufacturers to cloudify, operate, support, and commercialize their connected devices in a unified platform.   We enable OEMs across different industries to navigate their digital journey, transforming their devices into integrated business solutions that combine hardware, software and services. The only business and commerce platform designed specifically for IoT device manufacturers, our fully-federated Device Cloud empowers OEMs to manage the complete lifecycle of their devices, from the minute they leave the warehouse through aftermarket sales to end customers.  Our out-of-the-box applications for asset management, remote support, ecommerce and subscription management, financing, and a powerful and secure back office suite help OEMs boost revenue and market growth, optimize operational efficiencies, gain instant insights into equipment and device performance, and develop sustainable customer relationships.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * DeviceSendChildTelemetriesResponseB4adc7484462493381739d40e0a17d22
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class DeviceSendChildTelemetriesResponseB4adc7484462493381739d40e0a17d22 {
  public static final String SERIALIZED_NAME_CONFIG_VERSION = "config_version";
  @SerializedName(SERIALIZED_NAME_CONFIG_VERSION)
  private Integer configVersion = 0;

  public static final String SERIALIZED_NAME_COMMAND = "command";
  @SerializedName(SERIALIZED_NAME_COMMAND)
  private Boolean command = true;

  public static final String SERIALIZED_NAME_INFO_VERSION = "info_version";
  @SerializedName(SERIALIZED_NAME_INFO_VERSION)
  private Integer infoVersion = 0;

  public static final String SERIALIZED_NAME_NEW_LICENSES = "new_licenses";
  @SerializedName(SERIALIZED_NAME_NEW_LICENSES)
  private Boolean newLicenses = true;

  public static final String SERIALIZED_NAME_LATEST_FW_VERSION = "latest_fw_version";
  @SerializedName(SERIALIZED_NAME_LATEST_FW_VERSION)
  private Object latestFwVersion = null;

  public static final String SERIALIZED_NAME_LATEST_FW_FILE_ID = "latest_fw_file_id";
  @SerializedName(SERIALIZED_NAME_LATEST_FW_FILE_ID)
  private Object latestFwFileId = null;

  public static final String SERIALIZED_NAME_SPACE_DATA_VERSION = "space_data_version";
  @SerializedName(SERIALIZED_NAME_SPACE_DATA_VERSION)
  private Integer spaceDataVersion = 0;

  public static final String SERIALIZED_NAME_SUCCESS = "success";
  @SerializedName(SERIALIZED_NAME_SUCCESS)
  private Boolean success = true;

  public DeviceSendChildTelemetriesResponseB4adc7484462493381739d40e0a17d22() {
  }

  public DeviceSendChildTelemetriesResponseB4adc7484462493381739d40e0a17d22 configVersion(Integer configVersion) {
    
    
    
    
    this.configVersion = configVersion;
    return this;
  }

   /**
   * Get configVersion
   * @return configVersion
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "0", value = "")

  public Integer getConfigVersion() {
    return configVersion;
  }


  public void setConfigVersion(Integer configVersion) {
    
    
    
    this.configVersion = configVersion;
  }


  public DeviceSendChildTelemetriesResponseB4adc7484462493381739d40e0a17d22 command(Boolean command) {
    
    
    
    
    this.command = command;
    return this;
  }

   /**
   * Get command
   * @return command
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "false", value = "")

  public Boolean getCommand() {
    return command;
  }


  public void setCommand(Boolean command) {
    
    
    
    this.command = command;
  }


  public DeviceSendChildTelemetriesResponseB4adc7484462493381739d40e0a17d22 infoVersion(Integer infoVersion) {
    
    
    
    
    this.infoVersion = infoVersion;
    return this;
  }

   /**
   * Get infoVersion
   * @return infoVersion
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "0", value = "")

  public Integer getInfoVersion() {
    return infoVersion;
  }


  public void setInfoVersion(Integer infoVersion) {
    
    
    
    this.infoVersion = infoVersion;
  }


  public DeviceSendChildTelemetriesResponseB4adc7484462493381739d40e0a17d22 newLicenses(Boolean newLicenses) {
    
    
    
    
    this.newLicenses = newLicenses;
    return this;
  }

   /**
   * Get newLicenses
   * @return newLicenses
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "false", value = "")

  public Boolean getNewLicenses() {
    return newLicenses;
  }


  public void setNewLicenses(Boolean newLicenses) {
    
    
    
    this.newLicenses = newLicenses;
  }


  public DeviceSendChildTelemetriesResponseB4adc7484462493381739d40e0a17d22 latestFwVersion(Object latestFwVersion) {
    
    
    
    
    this.latestFwVersion = latestFwVersion;
    return this;
  }

   /**
   * Get latestFwVersion
   * @return latestFwVersion
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getLatestFwVersion() {
    return latestFwVersion;
  }


  public void setLatestFwVersion(Object latestFwVersion) {
    
    
    
    this.latestFwVersion = latestFwVersion;
  }


  public DeviceSendChildTelemetriesResponseB4adc7484462493381739d40e0a17d22 latestFwFileId(Object latestFwFileId) {
    
    
    
    
    this.latestFwFileId = latestFwFileId;
    return this;
  }

   /**
   * Get latestFwFileId
   * @return latestFwFileId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getLatestFwFileId() {
    return latestFwFileId;
  }


  public void setLatestFwFileId(Object latestFwFileId) {
    
    
    
    this.latestFwFileId = latestFwFileId;
  }


  public DeviceSendChildTelemetriesResponseB4adc7484462493381739d40e0a17d22 spaceDataVersion(Integer spaceDataVersion) {
    
    
    
    
    this.spaceDataVersion = spaceDataVersion;
    return this;
  }

   /**
   * Get spaceDataVersion
   * @return spaceDataVersion
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2", value = "")

  public Integer getSpaceDataVersion() {
    return spaceDataVersion;
  }


  public void setSpaceDataVersion(Integer spaceDataVersion) {
    
    
    
    this.spaceDataVersion = spaceDataVersion;
  }


  public DeviceSendChildTelemetriesResponseB4adc7484462493381739d40e0a17d22 success(Boolean success) {
    
    
    
    
    this.success = success;
    return this;
  }

   /**
   * Get success
   * @return success
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "true", value = "")

  public Boolean getSuccess() {
    return success;
  }


  public void setSuccess(Boolean success) {
    
    
    
    this.success = success;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the DeviceSendChildTelemetriesResponseB4adc7484462493381739d40e0a17d22 instance itself
   */
  public DeviceSendChildTelemetriesResponseB4adc7484462493381739d40e0a17d22 putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeviceSendChildTelemetriesResponseB4adc7484462493381739d40e0a17d22 deviceSendChildTelemetriesResponseB4adc7484462493381739d40e0a17d22 = (DeviceSendChildTelemetriesResponseB4adc7484462493381739d40e0a17d22) o;
    return Objects.equals(this.configVersion, deviceSendChildTelemetriesResponseB4adc7484462493381739d40e0a17d22.configVersion) &&
        Objects.equals(this.command, deviceSendChildTelemetriesResponseB4adc7484462493381739d40e0a17d22.command) &&
        Objects.equals(this.infoVersion, deviceSendChildTelemetriesResponseB4adc7484462493381739d40e0a17d22.infoVersion) &&
        Objects.equals(this.newLicenses, deviceSendChildTelemetriesResponseB4adc7484462493381739d40e0a17d22.newLicenses) &&
        Objects.equals(this.latestFwVersion, deviceSendChildTelemetriesResponseB4adc7484462493381739d40e0a17d22.latestFwVersion) &&
        Objects.equals(this.latestFwFileId, deviceSendChildTelemetriesResponseB4adc7484462493381739d40e0a17d22.latestFwFileId) &&
        Objects.equals(this.spaceDataVersion, deviceSendChildTelemetriesResponseB4adc7484462493381739d40e0a17d22.spaceDataVersion) &&
        Objects.equals(this.success, deviceSendChildTelemetriesResponseB4adc7484462493381739d40e0a17d22.success)&&
        Objects.equals(this.additionalProperties, deviceSendChildTelemetriesResponseB4adc7484462493381739d40e0a17d22.additionalProperties);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(configVersion, command, infoVersion, newLicenses, latestFwVersion, latestFwFileId, spaceDataVersion, success, additionalProperties);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeviceSendChildTelemetriesResponseB4adc7484462493381739d40e0a17d22 {\n");
    sb.append("    configVersion: ").append(toIndentedString(configVersion)).append("\n");
    sb.append("    command: ").append(toIndentedString(command)).append("\n");
    sb.append("    infoVersion: ").append(toIndentedString(infoVersion)).append("\n");
    sb.append("    newLicenses: ").append(toIndentedString(newLicenses)).append("\n");
    sb.append("    latestFwVersion: ").append(toIndentedString(latestFwVersion)).append("\n");
    sb.append("    latestFwFileId: ").append(toIndentedString(latestFwFileId)).append("\n");
    sb.append("    spaceDataVersion: ").append(toIndentedString(spaceDataVersion)).append("\n");
    sb.append("    success: ").append(toIndentedString(success)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("config_version");
    openapiFields.add("command");
    openapiFields.add("info_version");
    openapiFields.add("new_licenses");
    openapiFields.add("latest_fw_version");
    openapiFields.add("latest_fw_file_id");
    openapiFields.add("space_data_version");
    openapiFields.add("success");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to DeviceSendChildTelemetriesResponseB4adc7484462493381739d40e0a17d22
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!DeviceSendChildTelemetriesResponseB4adc7484462493381739d40e0a17d22.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in DeviceSendChildTelemetriesResponseB4adc7484462493381739d40e0a17d22 is not found in the empty JSON string", DeviceSendChildTelemetriesResponseB4adc7484462493381739d40e0a17d22.openapiRequiredFields.toString()));
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!DeviceSendChildTelemetriesResponseB4adc7484462493381739d40e0a17d22.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'DeviceSendChildTelemetriesResponseB4adc7484462493381739d40e0a17d22' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<DeviceSendChildTelemetriesResponseB4adc7484462493381739d40e0a17d22> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(DeviceSendChildTelemetriesResponseB4adc7484462493381739d40e0a17d22.class));

       return (TypeAdapter<T>) new TypeAdapter<DeviceSendChildTelemetriesResponseB4adc7484462493381739d40e0a17d22>() {
           @Override
           public void write(JsonWriter out, DeviceSendChildTelemetriesResponseB4adc7484462493381739d40e0a17d22 value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public DeviceSendChildTelemetriesResponseB4adc7484462493381739d40e0a17d22 read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             DeviceSendChildTelemetriesResponseB4adc7484462493381739d40e0a17d22 instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of DeviceSendChildTelemetriesResponseB4adc7484462493381739d40e0a17d22 given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of DeviceSendChildTelemetriesResponseB4adc7484462493381739d40e0a17d22
  * @throws IOException if the JSON string is invalid with respect to DeviceSendChildTelemetriesResponseB4adc7484462493381739d40e0a17d22
  */
  public static DeviceSendChildTelemetriesResponseB4adc7484462493381739d40e0a17d22 fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, DeviceSendChildTelemetriesResponseB4adc7484462493381739d40e0a17d22.class);
  }

 /**
  * Convert an instance of DeviceSendChildTelemetriesResponseB4adc7484462493381739d40e0a17d22 to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

